<?php
// Start output buffering to prevent any unwanted output before JSON
ob_start();

include("../../config/config.php");
include("../classes/User.php");
include("../classes/Post.php");
include("../classes/GetDate.php");

// Clear any output that might have been generated by includes
ob_clean();

header('Content-Type: application/json');

$json_data = file_get_contents('php://input');
$data = json_decode($json_data, true);

// Use the 'id' parameter directly as post_id
$post_id = $data['id'];
$userLoggedIn = $data['userLoggedIn'];

$post = new Post($con, $userLoggedIn);
$result = $post->getSinglePost($post_id);

try {
    echo json_encode($result);
} catch (Exception $e) {
    echo json_encode([
        'status' => 'error', 
        'message' => $e->getMessage()
    ]);
}
